spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/voto
    username: root
    password: 123456

  jpa:
    hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate.ddl-auto: update
    hibernate:
      jdbc: time_zone = TimeZone

user:
  info:
    base:
      url: https://user-info.herokuapp.com/users/

rateio:
  scheduler:
    cron: "* * 7 * * *"