spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/voto
    username: root
    password: 123456
  jpa:
    hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate.ddl-auto: update
    hibernate:
      jdbc: time_zone = TimeZone
  kafka:
    producer:
      bootstrap-servers: 127.0.0.1:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      group-id: group_id

user:
  info:
    base:
      url: https://user-info.herokuapp.com/users/

rateio:
  scheduler:
    cron: "* * 7 * * *"

topic:
  name:
    producer: topico.rateio.voto

auto:
  create:
    topics:
      enable: true